# Generated by Django 3.2.8 on 2021-11-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userx',
            name='d_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
